### ISSUE TITLE
Support npm@3

### ISSUE THREAD

**Issue by tadatuta** [enb/enb-bem-specs#50]
{ [Error: Command failed: /bin/sh -c /Users/tadatuta/projects/bem/bem-components/node_modules/enb-bem-specs/node_modules/.bin/mocha-phantomjs --reporter spec file:////Users/tadatuta/projects/bem/bem-components/desktop.specs/dropdown/dropdown.html
/bin/sh: /Users/tadatuta/projects/bem/bem-components/node_modules/enb-bem-specs/node_modules/.bin/mocha-phantomjs: No such file or directory
]
  killed: false,
  code: 127,
  signal: null,
  cmd: '/bin/sh -c /Users/tadatuta/projects/bem/bem-components/node_modules/enb-bem-specs/node_modules/.bin/mocha-phantomjs --reporter spec file:////Users/tadatuta/projects/bem/bem-components/desktop.specs/dropdown/dropdown.html' }
err Error: Command failed: /bin/sh -c /Users/tadatuta/projects/bem/bem-components/node_modules/enb-bem-specs/node_modules/.bin/mocha-phantomjs --reporter spec file:////Users/tadatuta/projects/bem/bem-components/desktop.specs/dropdown/dropdown.html
/bin/sh: /Users/tadatuta/projects/bem/bem-components/node_modules/enb-bem-specs/node_modules/.bin/mocha-phantomjs: No such file or directory

**Comment by tadatuta** [comment]
actually fixed in https://github.com/enb-bem/enb-bem-specs/commit/9bb3b821952c9fafaa71fc53484304209b2d7c40 by @just-boris 

new version needed

**Comment by apsavin** [comment]
@blond how about 0.8.1?

**Comment by apsavin** [comment]
As I can see, all's [ok](https://travis-ci.org/enb/enb-bem-specs/builds/119785230)

**Comment by apsavin** [comment]
@blond do we have any reason why we can't publish a version? Do you need help?

**Comment by apsavin** [comment]
@blond just want to remind about the issue. Can you please answer at least?

**Comment by blond** [comment]
Fixed in [v0.9.0](https://github.com/enb/enb-bem-specs/releases/tag/v0.9.0).

**Comment by apsavin** [comment]
@blond Thanks!
